[package]
authors=["Shelby Jenkins"]
description="Utilities for Llama.cpp, Openai, Anthropic, Mistral-rs."
edition="2021"
homepage="https://github.com/shelbyJenkins/llm_utils"
name="llm_utils"
readme="README.md"
version="0.0.5"

categories=["multimedia::encoding", "science"]
keywords=["anthropic", "ggml", "gguf", "llm", "openai"]
license="MIT"
repository="https://github.com/shelbyJenkins/llm_utils"

[dependencies]
anyhow="1.0.86"
dotenv="0.15.0"
gbnf="0.1.7"
gguf-rs="0.1.3"
hf-hub={version="0.3.2"}
minijinja="2.0.1"
regex="1.10.4"
serde={version="1.0.202"}
serde_json="1.0.117"
tiktoken-rs="0.5.9"
tokenizers="0.19.1"
