test_content="""
Arm IPO Is a Key Moment for Tech Stocks. Here Are the Risks.

The initial public offering of semiconductor designer Arm is an opportunity to wonder if this year’s technology-stock rally still has legs.

The gains are impressive so far. The tech-heavy Nasdaq is up 32% since Jan. 1, and it had its best first eight months of the year since 2003. The S&P 500 Technology Hardware & Equipment industry group has risen almost 30%.

Arm’s shares, which start trading on the Nasdaq Thursday, were priced at the top end of the range. That suggests investors are still willing to fork out for shares in the sector.

Having said that, September is usually a bad time for stocks, and tech stocks haven’t had a great month so far. Will the Arm IPO prove to be the last hurrah for the rally?

The risks are plentiful. A sluggish economic recovery in China, as well as the persistent tit-for-tat in the tech cold war between China and the U.S., will continue to cast a shadow over the outlook. China is important for more tech companies—both as a manufacturing base and as a market to sell into. Arm warned that a difficult relationship with its Arm China unit presents a risk to future profits.

It may be some relief that the Federal Reserve might be finished raising interest rates, or is at least close to finishing. But data out Wednesday suggest the inflation dragon isn’t yet slain, which means higher rates remain a risk.

And then there’s the hype around artificial intelligence, which has provided such a huge lift to tech stocks. The question is how long it can last. Nvidia, arguably the biggest beneficiary of AI optimism and the company that tried to buy Arm just a few years ago, has had a particularly rough September.

The tech-stock rally is hanging in the balance. Arm could tip it one way or the other.

—Brian Swint

*** Join Barron’s deputy editor Alex Eule and associate editor for technology Eric J. Savitz today at noon when they discuss the outlook for tech companies and individual stocks. Sign up here.

Try your hand at this morning’s Barron’s crossword puzzle and sudoku games. For all games, including a digital jigsaw based on the week’s cover story, click here.

MEMBER MESSAGE

Invest Like An Expert With Barron's

Not a subscriber? Take advantage of our special intro offer and get expert stock picks, personal finance and investment advice and updates on the market’s biggest stories. Learn More

Auto Industry Braces as UAW Strike Deadline Looms

Auto industry experts are bracing for the possibility that 150,000 workers could walk off the job as early as midnight tonight as the contract between the United Auto Workers and Ford Motor, General Motors, and Chrysler-maker Stellantis expires.

 • A UAW strike against the Big Three auto makers could cost the U.S. economy about $500 million a day, RSM chief economist Joe Brusuelas told Barron’s. A month-long strike could cost $15 billion, a 0.2% drag on the economy in the third quarter, but not enough to trigger a recession.
 • The latest union efforts are as much about working conditions and expectations as they are about higher wages. A labor stoppage at one or all of the auto makers could spill over into adjacent industries, as well as parts, electronics, and software suppliers, and delay a broader economic recovery, Brusuelas said.
 • Another estimate by the Anderson Economic Group predicts that a 10-day strike would result in $5 billion of economic losses. Founder Patrick Anderson told Barron’s that strikes are “extremely costly” to workers. UAW members authorized a strike, “but nobody voted to lose a month and half of pay.”
 • If the UAW succeeds in securing a lucrative contract with 10% wage increases over the life of the contract, it could raise the price of new vehicles by roughly 4% on average, according to Barron’s calculations, and could encourage other unions to bargain more assertively.
What’s Next: The strike deadline also looms over the nine-day North American International Auto Show in Detroit. Fifteen automotive brands have displays, but only six new models are scheduled to be revealed, along with a new Jeep and a refreshed Ford F-150 pickup. The show runs through Sept. 24.

—Megan Leonhardt and Janet H. Cho

August’s Inflation Report Shows Fed Isn’t Done Yet

August’s consumer price index showed inflation continued to cool mildly from the sky-high price gains that plagued consumers and policy makers for the past two years. Core prices, excluding volatile food and energy, slowed to a 4.3% annual pace, the lowest level since September 2021.

 • Continued slowdowns, combined with recent softening in the labor market, will likely convince Federal Reserve officials to hold interest rates steady next week. Markets are expecting a pause, but are divided on the probability of another increase before the end of the year.
 • Consumers have shown resilience, even while facing a spike in gasoline costs in August that drove up the headline consumer price index by 0.6% from July, the largest such increase in more than a year. Shelter costs rose 0.3% over the month, notching their 40th straight month of gains.
 • Deloitte forecasts holiday retail sales will rise 3.5% to 4.6% this year, slower than last year’s 7.6% pace. Sales from November to January are expected to total $1.54 trillion to $1.56 trillion. Bain also sees holiday sales slowing to 3%, the lowest growth rate since 2018.
 • Last year’s retail holiday sales totaled $1.49 trillion, Deloitte said, adding that the bigger percentage jump last year was mostly because of inflation. 2023 e-commerce holiday sales are projected to rise 10.3% to 12.8% over last year, to $278 billion to $284 billion.
What’s Next: Inflation-focused traders expect the annual CPI rate to remain above 3% between now and January, MarketWatch reported. The Fed wants inflation back to its 2% annual target, and JPMorgan said it won’t fall below that threshold until late next year.

—Megan Cassella and Liz Moyer

Netflix’s CFO Offers Softer Guidance as Ad Business Grows

Netflix’s stock fell after Chief Financial Officer Spencer Neumann offered softer-than-expected guidance on margins and said the streaming company’s fledgling advertising business was difficult to build from scratch and not yet material to overall revenue.

 • Neumann said the company is guiding to operating margins in the 18% to 20% range, below the current consensus of 22%, but he expects margins to “tick up going forward” as Netflix accelerates revenue growth in 2024 and beyond. Shares fell 5.2% on Wednesday.
 • Neumann said it’s “not easy” to build an advertising business from scratch, as Netflix is trying to do amid competition from Walt Disney and Apple. He said a “healthy proportion” of accounts are moving toward Netflix’s ad-supported subscription tier, and that revenue is building in 2024.
 • The CFO said the continuing Hollywood writers’ and actors’ strikes are hurting business. “The business isn’t moving forward,” he told a Bank of America conference in New York. Neither union is talking to the Alliance of Motion Picture and Television Producers, which includes Netflix.
 • After Neumann’s comments, Pivotal Research Group analyst Jeffrey Wlodarczak cut his average revenue-per-user growth projections to 2% from 4%, and lowered Netflix’s fourth-quarter revenue forecast to $8.73 billion from $8.89 billion. He has a buy rating and $600 price target on shares.
What’s Next: Neumann said Netflix is focused on lifestyle sports programming, but won’t be investing billions in live high-profile sporting events, because he doesn’t see an immediate return. He said gaming is a “developing business” and “long-term growth opportunity” with a five- to 10-year time frame.

—Janet H. Cho

China Warns EU Over Inquiry into Electric-Vehicle Subsidies

China hit back at the European Union Thursday, warning that the bloc’s inquiry into Beijing’s subsidies for electric cars will hurt China-EU economic and trade relations.

 • The European Commission announced an investigation Wednesday into electric vehicles coming from China. “Global markets are now flooded with cheaper Chinese electric cars. And their price is kept artificially low by huge state subsidies,” President Ursula von der Leyen said in a speech.
 • China described the investigation as “naked protectionist behavior that will seriously disrupt and distort the global automotive industry supply chain,” in a commerce ministry statement.
 • China’s BYD is the single fastest-growing EV manufacturer in Europe, according to Matthias Schmidt, the publisher of the European Electric Car Report. Chinese manufacturers’ electric-car registrations ballooned more than 130% year over year in the first seven months of 2023.
 • Tesla, with a market share of 19% in Europe as of the end of July, could be a beneficiary of any protectionist measures emerging from the EU investigation. The company’s Model Y is, by far, the region’s best selling EV.
What’s Next: Chinese EV makers have enjoyed early success in their European—and, indeed, global—expansion. The EU’s investigation, and its outcome, is a sign they may not continue to have things their own way, and is a big moment in the EV race.

—Callum Keown and Jack Denton

Pro Pickleball Leagues Flip Their Merger Back On

Major League Pickleball and rival PPA Tour, the sport’s two largest pro associations, have rekindled their merger hopes, this time with the backing of a $50 million investment from private-equity firm SC Holdings, PPA Tour owner Tom Dundon, and some MLP owners.

 • The fast-growing sport, combining tennis, badminton, and ping pong, has attracted investment from high-profile athletes such as Tom Brady and LeBron James. More than 8.9 million people played pickleball in 2022, a 159% jump over three years, the Sports & Fitness Industry Association said.
 • The MLP and PPA Tour brands will continue to exist but the merger helps eliminate scheduling conflicts and sniping over athletes. PPA Tour is an individualistic bracket-style league, while MLP is based on coed teams. Combined, they have 150 of the world’s top players.
 • MLP founder Steve Kuhn said the merger offers players a “better future playing professional pickleball.” The holding company will increase opportunities for competition, broadcasting rights, and sponsorship, PPA’s Dundon said.
 • The leagues originally announced plans to merge last November, but by this summer the talks were falling apart. MLP said it was signing top players to multiyear guaranteed contracts.
What’s Next: The combined league’s board of directors is set to include SC Holdings’ Jason Stein, who also advises basketball star LeBron James’ video-production firm SpringHill; the D.C. Pickleball Team owner Al Tylis; PPA Tour’s Dundon; MLP’s Kuhn; and former Goldman Sachs partner Brian Levine.

—Janet H. Cho

Households with new teenage drivers quickly find out their auto insurance rates are going to rise. To save, you have to shop around and ask about every possible discount. That may mean getting a friendly agent on the phone to ask about the impact of good grades, certified driver-education courses, away-at-school pricing, bundling with home insurance or other cars, loyalty programs, safe-driving records and so on.

For some tips to get coverage without breaking the bank, read here.

—Beth Pinsker
"""
